image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - npm i

build-file:
  stage: build
  script:
    - npm run build
    - echo "Finish build!"
  artifacts:
      name: "$CI_JOB_NAME"
      untracked: true
      expire_in: 1 week
      paths:
        - dist/

show-ver:
  stage: test
  script:
    - node -v
    - echo "Finish version check!"

deploy-to-firebase:
  stage: deploy
  dependencies:
    - build-file
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy
    - echo "Finish deploy!"
    
