image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - npm i

build:
  stage: build
  script:
    - npm run build
    - echo "Finish build!"
  artifacts:
      paths:
        - dist/

show-ver:
  stage: test
  script:
    - node -v
    - echo "Finish version check!"
